services:
  app:
    image: revision_app:latest
    build: .
    container_name: revision_app
    ports:
      - "127.0.0.1:3200:3000"
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - revision_app-data:/app/data
    restart: unless-stopped

volumes:
  revision_app-data:
    external: true
